name: Build & Push Redash ARM64

on:
  push:
    branches: [main]  # or your default branch
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and push Redash ARM64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  # or the correct path to your Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/redash-arm64:latest
